-- Motorparts v2 PostgreSQL schema artifact (initial executable baseline)
-- Generated for phased rollout scaffolding.
-- Target: PostgreSQL 14+

BEGIN;

-- =========================
-- Enum Types
-- =========================
DO $$ BEGIN
    CREATE TYPE stock_movement_type_enum AS ENUM (
      'sale','sale_return','purchase_receipt','purchase_return',
      'adjustment_add','adjustment_sub','opening_stock','damage_write_off','count_correction'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE stock_movement_reference_enum AS ENUM (
      'sales_transaction','sales_return','purchase_order','stock_adjustment','manual'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE cost_change_source_enum AS ENUM ('manual_update','po_receipt','initial_entry');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- =========================
-- Generic updated_at trigger
-- =========================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

-- =========================
-- Core Tables (baseline)
-- =========================
CREATE TABLE IF NOT EXISTS products (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id       BIGINT NOT NULL,
    brand_id          BIGINT NULL,
    uom_id            SMALLINT NOT NULL,
    tax_rate_id       SMALLINT NOT NULL,
    sku               VARCHAR(80) NOT NULL UNIQUE,
    name              VARCHAR(220) NOT NULL,
    description       TEXT NULL,
    short_desc        VARCHAR(400) NULL,
    part_number       VARCHAR(100) NULL,
    cost_price        NUMERIC(12,4) NOT NULL DEFAULT 0.0000,
    selling_price     NUMERIC(12,4) NOT NULL DEFAULT 0.0000,
    wholesale_price   NUMERIC(12,4) NULL,
    min_selling_price NUMERIC(12,4) NULL,
    is_taxable        BOOLEAN NOT NULL DEFAULT TRUE,
    is_serialized     BOOLEAN NOT NULL DEFAULT FALSE,
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,
    weight_kg         NUMERIC(8,3) NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at        TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_brand ON products(brand_id);
CREATE INDEX IF NOT EXISTS idx_products_part_number ON products(part_number);
CREATE INDEX IF NOT EXISTS idx_products_is_active ON products(is_active);

CREATE TABLE IF NOT EXISTS product_variants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT NOT NULL,
    variant_sku     VARCHAR(100) NOT NULL UNIQUE,
    variant_name    VARCHAR(200) NULL,
    attributes      JSONB NULL,
    cost_price      NUMERIC(12,4) NULL,
    selling_price   NUMERIC(12,4) NULL,
    wholesale_price NUMERIC(12,4) NULL,
    margin_pct      NUMERIC(8,4) GENERATED ALWAYS AS (
      CASE
        WHEN COALESCE(selling_price, 0) > 0
          THEN ROUND(((selling_price - COALESCE(cost_price, 0)) / selling_price) * 100, 4)
        ELSE 0
      END
    ) STORED,
    markup_pct      NUMERIC(8,4) GENERATED ALWAYS AS (
      CASE
        WHEN COALESCE(cost_price, 0) > 0
          THEN ROUND(((COALESCE(selling_price, 0) - cost_price) / cost_price) * 100, 4)
        ELSE 0
      END
    ) STORED,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMPTZ NULL,
    CONSTRAINT fk_product_variants_product
      FOREIGN KEY (product_id) REFERENCES products(id)
      ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_product_variants_product ON product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_pv_margin_pct ON product_variants(margin_pct);

CREATE TABLE IF NOT EXISTS inventory_stock (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id  BIGINT NOT NULL UNIQUE,
    qty_on_hand         NUMERIC(12,4) NOT NULL DEFAULT 0,
    qty_reserved        NUMERIC(12,4) NOT NULL DEFAULT 0,
    qty_available       NUMERIC(12,4) GENERATED ALWAYS AS (qty_on_hand - qty_reserved) STORED,
    reorder_point       NUMERIC(12,4) NOT NULL DEFAULT 0,
    reorder_qty         NUMERIC(12,4) NOT NULL DEFAULT 0,
    max_stock_level     NUMERIC(12,4) NULL,
    avg_cost            NUMERIC(14,6) NOT NULL DEFAULT 0,
    last_counted_at     TIMESTAMPTZ NULL,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_stock_variant
      FOREIGN KEY (product_variant_id) REFERENCES product_variants(id)
      ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT chk_inventory_qty CHECK (qty_on_hand >= 0),
    CONSTRAINT chk_inventory_reserved CHECK (qty_reserved >= 0)
);

CREATE INDEX IF NOT EXISTS idx_inventory_low_stock ON inventory_stock(qty_on_hand, reorder_point);

CREATE TABLE IF NOT EXISTS stock_movements (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id  BIGINT NOT NULL,
    movement_type       stock_movement_type_enum NOT NULL,
    reference_type      stock_movement_reference_enum NOT NULL,
    reference_id        BIGINT NOT NULL,
    qty_before          NUMERIC(12,4) NOT NULL,
    qty_change          NUMERIC(12,4) NOT NULL,
    qty_after           NUMERIC(12,4) NOT NULL,
    unit_cost           NUMERIC(14,6) NULL,
    notes               TEXT NULL,
    performed_by        BIGINT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_movements_variant
      FOREIGN KEY (product_variant_id) REFERENCES product_variants(id)
      ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_stock_movements_variant ON stock_movements(product_variant_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_type ON stock_movements(movement_type);
CREATE INDEX IF NOT EXISTS idx_stock_movements_ref ON stock_movements(reference_type, reference_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_date ON stock_movements(created_at);

CREATE TABLE IF NOT EXISTS supplier_cost_history (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id         BIGINT NOT NULL,
    product_variant_id  BIGINT NOT NULL,
    supplier_product_id BIGINT NULL,
    old_unit_cost       NUMERIC(12,4) NOT NULL,
    new_unit_cost       NUMERIC(12,4) NOT NULL,
    cost_change_pct     NUMERIC(8,4) GENERATED ALWAYS AS (
      ROUND(
        CASE
          WHEN old_unit_cost = 0 THEN 0
          ELSE ((new_unit_cost - old_unit_cost) / old_unit_cost) * 100
        END
      , 4)
    ) STORED,
    change_source       cost_change_source_enum NOT NULL DEFAULT 'manual_update',
    purchase_order_id   BIGINT NULL,
    change_reason       VARCHAR(300) NULL,
    changed_by          BIGINT NOT NULL,
    effective_date      DATE NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sch_supplier ON supplier_cost_history(supplier_id);
CREATE INDEX IF NOT EXISTS idx_sch_variant ON supplier_cost_history(product_variant_id);
CREATE INDEX IF NOT EXISTS idx_sch_supplier_variant_date ON supplier_cost_history(supplier_id, product_variant_id, effective_date DESC);
CREATE INDEX IF NOT EXISTS idx_sch_po ON supplier_cost_history(purchase_order_id);

-- =========================
-- Trigger bindings
-- =========================
DROP TRIGGER IF EXISTS trg_products_set_updated_at ON products;
CREATE TRIGGER trg_products_set_updated_at
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_product_variants_set_updated_at ON product_variants;
CREATE TRIGGER trg_product_variants_set_updated_at
BEFORE UPDATE ON product_variants
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMIT;
