export const ENDPOINTS = {
  auth: {
    register: 'auth/register/',
    login: 'auth/login/',
    logout: 'auth/logout/',
    refresh: 'auth/token/refresh/',
    profile: 'auth/profile/',
    changePassword: 'auth/change-password/',
    users: 'auth/users/',
    userById: (id: number) => `auth/users/${id}/`,
    resetUserPassword: (id: number) => `auth/users/${id}/reset-password/`,
    roles: 'auth/roles/',
    rolePermissions: (id: number) => `auth/roles/${id}/permissions/`,
    permissions: 'auth/permissions/',
  },
  products: {
    categories: 'products/categories/',
    categoryById: (id: number) => `products/categories/${id}/`,
    items: 'products/items/',
    itemById: (id: number) => `products/items/${id}/`,
    sizes: 'products/items/sizes/',
  },
  pos: {
    bootstrap: 'pos/bootstrap/',
    checkout: 'pos/checkout/',
    paymentMethods: 'pos/payment-methods/',
    currentCashSession: 'pos/cash-session/current/',
    openCashSession: 'pos/cash-sessions/open/',
    dashboard: 'pos/dashboard/',
    transactions: 'pos/transactions/',
    transactionById: (id: number) => `pos/transactions/${id}/`,
  },
  customers: {
    list: 'customers/',
    byId: (id: number) => `customers/${id}/`,
  },
  returns: {
    list: 'returns/',
    byId: (id: number) => `returns/${id}/`,
  },
  system: {
    health: 'system/health/',
    rollout: 'system/rollout/',
    reconciliation: 'system/reconciliation/',
    audit: 'system/audit/',
    cutoverControls: 'system/cutover-controls/',
  },
} as const;
