# Generated by Django 6.0.2 on 2026-04-01 12:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_productvariant_productbarcode_and_more'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('pos', '0002_salestransaction_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('tax_number', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'business_profiles',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_type', models.CharField(max_length=40, unique=True)),
                ('prefix', models.CharField(default='INV', max_length=20)),
                ('current_value', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'invoice_sequences',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('invoice_type', models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('sales_return', 'Sales Return')], max_length=40)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sales_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pos.salestransaction')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
            options={
                'db_table': 'invoice_items',
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('reference_number', models.CharField(blank=True, max_length=120, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.paymentmethod')),
            ],
            options={
                'db_table': 'invoice_payments',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type', 'issued_at'], name='idx_invoice_type_issued_at'),
        ),
    ]
