# Generated by Django 6.0.2 on 2026-04-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='discount_amount',
        ),
    ]
