# Generated by Django 6.0.2 on 2026-04-01 11:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vehicle_makes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='vehicles.vehiclemake')),
            ],
            options={
                'db_table': 'vehicle_models',
                'ordering': ['make__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2027)])),
                ('is_active', models.BooleanField(default=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='years', to='vehicles.vehiclemodel')),
            ],
            options={
                'db_table': 'vehicle_years',
                'ordering': ['-year'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('make', 'name'), name='uq_vehicle_model_make_name'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('make', 'slug'), name='uq_vehicle_model_make_slug'),
        ),
        migrations.AddConstraint(
            model_name='vehicleyear',
            constraint=models.UniqueConstraint(fields=('model', 'year'), name='uq_vehicle_year_model_year'),
        ),
    ]
