# Generated by Django 6.0.2 on 2026-04-01 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_productvariant_productbarcode_and_more'),
        ('vehicles', '0002_alter_vehicleyear_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVehicleFitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='catalog.product')),
                ('vehicle_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='vehicles.vehicleyear')),
            ],
            options={
                'db_table': 'product_vehicle_fitments',
                'indexes': [models.Index(fields=['vehicle_year', 'product'], name='idx_fitment_vehicle_product')],
                'constraints': [models.UniqueConstraint(fields=('product', 'vehicle_year'), name='uq_product_vehicle_fitment')],
            },
        ),
    ]
