# Generated by Django 6.0.2 on 2026-04-03 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_productvariant_productbarcode_and_more'),
        ('vehicles', '0003_productvehiclefitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvehiclefitment',
            name='fitment_notes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='productvehiclefitment',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_fitments', to='vehicles.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='productvehiclefitment',
            name='year_range',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='productvehiclefitment',
            index=models.Index(fields=['vehicle_model', 'product'], name='idx_fitment_model_product'),
        ),
    ]
