# Generated by Django 6.0.2 on 2026-04-03 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_productvehiclefitment_fitment_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvehiclefitment',
            name='vehicle_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitments', to='vehicles.vehicleyear'),
        ),
    ]
