# Generated by Django 6.0.2 on 2026-04-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_productvariant_productbarcode_and_more'),
        ('vehicles', '0005_alter_productvehiclefitment_vehicle_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicleyear',
            name='uq_vehicle_year_model_year',
        ),
        migrations.RemoveConstraint(
            model_name='productvehiclefitment',
            name='uq_product_vehicle_fitment',
        ),
        migrations.RemoveIndex(
            model_name='productvehiclefitment',
            name='idx_fitment_vehicle_product',
        ),
        migrations.AddConstraint(
            model_name='productvehiclefitment',
            constraint=models.UniqueConstraint(fields=('product', 'vehicle_model', 'year_range'), name='uq_product_vehicle_fitment_v2'),
        ),
        migrations.RemoveField(
            model_name='productvehiclefitment',
            name='vehicle_year',
        ),
        migrations.DeleteModel(
            name='VehicleYear',
        ),
    ]
