# Generated by Django 6.0.2 on 2026-04-01 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_productvariant_productbarcode_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=20)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'discounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payment_methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PosTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'pos_terminals',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('pos_terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='pos.posterminal')),
            ],
            options={
                'db_table': 'cash_sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'sales_returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_returned', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('restock', models.BooleanField(default=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.salesreturn')),
            ],
            options={
                'db_table': 'sales_return_items',
            },
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_number', models.CharField(max_length=30, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=180, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('voided', 'Voided'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=25)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('taxable_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('amount_tendered', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('change_given', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.cashsession')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_cashier', to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.discount')),
                ('pos_terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.posterminal')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_transactions', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'sales_transactions',
            },
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='sales_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pos.salestransaction'),
        ),
        migrations.CreateModel(
            name='SalesTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('line_subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('line_tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
                ('sales_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.salestransaction')),
            ],
            options={
                'db_table': 'sales_transaction_items',
            },
        ),
        migrations.CreateModel(
            name='TransactionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('reference_number', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.paymentmethod')),
                ('sales_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.salestransaction')),
            ],
            options={
                'db_table': 'transaction_payments',
            },
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['status', 'opened_at'], name='idx_cash_session_status_opened'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['sales_return', 'product_variant'], name='idx_sri_return_variant'),
        ),
        migrations.AddIndex(
            model_name='salestransaction',
            index=models.Index(fields=['warehouse', 'transaction_date', 'status'], name='idx_sales_txn_reporting'),
        ),
        migrations.AddIndex(
            model_name='salestransaction',
            index=models.Index(fields=['status'], name='idx_sales_txn_status'),
        ),
        migrations.AddIndex(
            model_name='salestransactionitem',
            index=models.Index(fields=['sales_transaction', 'product_variant'], name='idx_sti_txn_variant'),
        ),
        migrations.AddIndex(
            model_name='transactionpayment',
            index=models.Index(fields=['sales_transaction', 'payment_method'], name='idx_txn_payments_lookup'),
        ),
    ]
