# Generated by Django 6.0.2 on 2026-04-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_salestransaction_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransaction',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='salestransactionitem',
            name='discount_amount',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
