# Generated by Django 6.0.2 on 2026-04-03 08:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_productvariant_productbarcode_and_more'),
        ('customers', '0001_initial'),
        ('pos', '0003_remove_salestransaction_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300, null=True)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('tin', models.CharField(blank=True, max_length=50, null=True)),
                ('bir_accreditation_no', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=512, null=True)),
                ('receipt_footer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'business_profile',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('applies_to', models.CharField(choices=[('transaction', 'Transaction'), ('item', 'Item'), ('category', 'Category'), ('product', 'Product')], default='transaction', max_length=20)),
                ('target_id', models.BigIntegerField(blank=True, null=True)),
                ('min_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'discounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_code', models.CharField(max_length=20, unique=True)),
                ('series_label', models.CharField(max_length=60)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('current_number', models.BigIntegerField(default=0)),
                ('zero_pad', models.PositiveSmallIntegerField(default=6)),
                ('start_number', models.BigIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'receipt_sequences',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('receipt_type', models.CharField(choices=[('official_receipt', 'Official Receipt'), ('sales_invoice', 'Sales Invoice'), ('delivery_receipt', 'Delivery Receipt')], default='official_receipt', max_length=20)),
                ('buyer_name', models.CharField(default='Walk-in Customer', max_length=200)),
                ('buyer_address', models.TextField(blank=True, null=True)),
                ('buyer_tin', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_address', models.TextField()),
                ('seller_tin', models.CharField(blank=True, max_length=50, null=True)),
                ('seller_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('taxable_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('vat_exempt_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('zero_rated_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('change_given', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('void', 'Void')], default='issued', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('printed_count', models.PositiveSmallIntegerField(default=0)),
                ('last_printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_receipts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('sales_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='pos.salestransaction')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_receipts', to=settings.AUTH_USER_MODEL)),
                ('receipt_sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.receiptsequence')),
            ],
            options={
                'db_table': 'receipts',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveSmallIntegerField()),
                ('sku', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('unit_of_measure', models.CharField(default='pcs', max_length=20)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=4, max_digits=14)),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productvariant')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.receipt')),
            ],
            options={
                'db_table': 'receipt_items',
                'indexes': [models.Index(fields=['receipt'], name='idx_receipt_items_receipt')],
            },
        ),
        migrations.CreateModel(
            name='ReceiptPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_name', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.paymentmethod')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.receipt')),
            ],
            options={
                'db_table': 'receipt_payments',
                'indexes': [models.Index(fields=['receipt'], name='idx_receipt_payments_receipt')],
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['customer'], name='idx_receipts_customer'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['issued_at'], name='idx_receipts_issued_at'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status'], name='idx_receipts_status'),
        ),
    ]
