# Generated by Django 6.0.2 on 2026-04-03 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_businessprofile_discount_receiptsequence_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='session_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='pos_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sessions', to='pos.posterminal'),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='pos_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.posterminal'),
        ),
    ]
