# Generated by Django 6.0.2 on 2026-04-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_cashsession_session_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransaction',
            name='pos_terminal',
        ),
        migrations.RemoveField(
            model_name='cashsession',
            name='pos_terminal',
        ),
        migrations.DeleteModel(
            name='PosTerminal',
        ),
    ]
