# Generated by Django 6.0.2 on 2026-05-09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_remove_salestransaction_pos_terminal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salestransactionitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salestransactionitem',
            name='discount_type',
            field=models.CharField(
                blank=True,
                choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='salestransactionitem',
            name='discount_value',
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
