# Generated by Django 6.0.2 on 2026-04-01 12:07

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, null=True)),
                ('part_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('cost_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_serialized', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.taxrate')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unitofmeasure')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('variant_sku', models.CharField(max_length=100, unique=True)),
                ('variant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'db_table': 'product_variants',
            },
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('barcode', models.CharField(max_length=120, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'product_barcodes',
                'ordering': ['-is_primary', 'barcode'],
            },
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='idx_pv_attributes_gin'),
        ),
    ]
