# Generated by Django 5.0.6 on 2026-04-03 10:00

from django.db import migrations

DEPRECATED_TABLES = [
    # procurement
    'purchase_order_items',
    'purchase_orders',
    'supplier_products',
    'suppliers',
    # pricing
    'product_price_tier_rules',
    'price_tiers',
    'product_price_history',
    'supplier_cost_history',
    # invoices
    'invoice_payments',
    'invoice_items',
    'invoices',
    'invoice_sequences',
    'business_profiles',
]

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql=[(
                f'DROP TABLE IF EXISTS "{table_name}" CASCADE;'
            ) for table_name in DEPRECATED_TABLES],
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
