# Generated by Django 6.0.2 on 2026-04-01 12:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_productvariant_productbarcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_pos_location', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'warehouses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('add', 'Add'), ('subtract', 'Subtract')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock_adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('sale_return', 'Sale Return'), ('purchase_receipt', 'Purchase Receipt'), ('purchase_return', 'Purchase Return'), ('adjustment_add', 'Adjustment Add'), ('adjustment_sub', 'Adjustment Subtract'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('opening_stock', 'Opening Stock'), ('damage_write_off', 'Damage Write-Off'), ('count_correction', 'Count Correction')], max_length=30)),
                ('reference_type', models.CharField(choices=[('sales_transaction', 'Sales Transaction'), ('sales_return', 'Sales Return'), ('purchase_order', 'Purchase Order'), ('stock_adjustment', 'Stock Adjustment'), ('stock_transfer', 'Stock Transfer'), ('manual', 'Manual')], max_length=30)),
                ('reference_id', models.BigIntegerField()),
                ('qty_before', models.DecimalField(decimal_places=4, max_digits=12)),
                ('qty_change', models.DecimalField(decimal_places=4, max_digits=12)),
                ('qty_after', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock_movements',
                'indexes': [models.Index(fields=['product_variant', 'warehouse', '-created_at'], name='idx_stk_mov_prod_date'), models.Index(fields=['reference_type', 'reference_id'], name='idx_stock_movements_ref'), models.Index(fields=['movement_type'], name='idx_stock_movements_type')],
            },
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('qty_reserved', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_point', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('reorder_qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('max_stock_level', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('avg_cost', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('last_counted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock',
                'indexes': [models.Index(fields=['product_variant', 'warehouse', 'qty_on_hand'], name='idx_inventory_stock_lookup'), models.Index(fields=['warehouse', 'qty_on_hand', 'reorder_point'], name='idx_inventory_low_stock')],
                'constraints': [models.UniqueConstraint(fields=('product_variant', 'warehouse'), name='uq_inventory_stock_variant_warehouse'), models.CheckConstraint(condition=models.Q(('qty_on_hand__gte', 0)), name='chk_stock_qty_non_negative'), models.CheckConstraint(condition=models.Q(('qty_reserved__gte', 0)), name='chk_stock_reserved_non_negative')],
            },
        ),
    ]
