# Generated by Django 6.0.2 on 2026-04-01 12:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_productvariant_productbarcode_and_more'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'price_tiers',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('new_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('effective_date', models.DateField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant')),
            ],
            options={
                'db_table': 'product_price_history',
                'indexes': [models.Index(fields=['product_variant', '-effective_date'], name='idx_price_history_lookup')],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceTierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_qty', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_date', models.DateField()),
                ('price_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricetier')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant')),
            ],
            options={
                'db_table': 'product_price_tier_rules',
                'indexes': [models.Index(fields=['product_variant', 'price_tier', 'min_qty', 'effective_date'], name='idx_price_tier_resolution')],
            },
        ),
        migrations.CreateModel(
            name='SupplierCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_cost', models.DecimalField(decimal_places=6, max_digits=14)),
                ('new_cost', models.DecimalField(decimal_places=6, max_digits=14)),
                ('effective_date', models.DateField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.supplier')),
            ],
            options={
                'db_table': 'supplier_cost_history',
                'indexes': [models.Index(fields=['supplier', '-effective_date'], name='idx_supplier_cost_trend')],
            },
        ),
    ]
